repos:
  # 1. Ruff - Ultra-fast linter/formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
      
 # 2. Prettier - formats JS/JSX frontend files
  - repo: local
    hooks:
      - id: prettier-frontend
        name: prettier (frontend)
        entry: bash -c "cd tailor-app/frontend"
        language: system