repos:
  # 1. Ruff - Ultra-fast linter/formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
      
 # 2. Prettier - formats JS/JSX frontend files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0  # match Prettier version you're using
    hooks:
      - id: prettier
        name: prettier (frontend)
        entry: npx prettier
        language: node
        types: [javascript, jsx]
        additional_dependencies: []
        args: [
          "tailor-app/frontend/src/**/*.{js,jsx}",
          "--write",
          "--config",
          "tailor-app/frontend/.prettierrc"
        ]