name: Test and Deploy

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }} 
            - name: npm install
              run: |
                cd tailor-app/frontend
                npm ci
            - name: front-end tests
              run: |
                cd tailor-app/frontend  
                npm test
            - name: back-end package installation
              run: |
                cd tailor-app/backend
                python3 -m pip install -r requirements.txt
            - name: back-end testing
              run: |
                cd tailor-app/backend
                python3 -m pytest tests/

    deploy:
        needs: tests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' # only executes on push
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: install heroku CLI
              run: curl https://cli-assets.heroku.com/install.sh | sh
          
            - name: deploy to heroku
              uses: akhileshns/heroku-deploy@v3.12.13
              with:
                heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                heroku_app_name: "tailor"
                heroku_email: ${{ secrets.HEROKU_EMAIL }}
          
